import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import { Header } from '@/widgets/Header';
import dynamic from 'next/dynamic';
import { MainPage } from '@/screens/MainPage';
import { Catalog } from '@/screens/Catalog';

const inter = Inter({ subsets: ['latin'] });

export default function productCatalog () {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main >
                <Catalog/>
            </main>
        </>
    );
}
